import React from 'react'
import "../../App.css"

const About = () => {
    return ( 
        <div className="about-container">
            <p>
            Melody Interpolater uses the power of recurrent neural networks to generate music in the styles of classical composers. Our team trains neural network models to learn the styles of composers from their music samples. We then utilize a prediction algorithm to allow users to generate music based on what the model has learned. 
            </p>
            <p>
            Currently, we have trained models for Bach, Beethoven, Chopin and Mozart with plans to expand into styles of other classical composers. Users can generate music themselves by heading to "Generator" and following the instructions. Users can also listen to music samples generated by the team by heading to "Library".
            </p>
            <h4>
            Our Team:
            </h4>
            <div className="about-images">
              <div>
                <p>A Apte</p> 
                <img src={require('./img/aapte.png')} alt="pic of a" width='170px'/>
              </div>
              <div>
                <p>Joshua Solis</p> 
                <img src={require('./img/jsolis.png')} alt="pic of josh" width='170px'/>
              </div>
              <div>
                <p>Tony Tia</p>
                <img src={require('./img/ttia.png')} alt="pic of tony" width='170px'/>
              </div>
            </div>
        </div>
     );
}
 
export default About;